### ISSUE TITLE
Showing Error - KeyError: 'data'!

### ISSUE THREAD

**Issue by Xeek3y** [SmoZy92/Shodomain#6]
Hello i'm trying to gather subdomains using this script but it's throwing this error!
```
 python shodomain.py <MY-API-KEY> site.com
Traceback (most recent call last):
  File "shodomain.py", line 30, in <module>
    for item in data["data"]:
KeyError: 'data'
```

**Comment by uzzalhossain2020** [comment]
> Hello i'm trying to gather subdomains using this script but it's throwing this error!
> 
> ```
>  python shodomain.py <MY-API-KEY> site.com
> Traceback (most recent call last):
>   File "shodomain.py", line 30, in <module>
>     for item in data["data"]:
> KeyError: 'data'
> ```

How you solve this ?

**Comment by Xeek3y** [comment]
> 
> 
> > Hello i'm trying to gather subdomains using this script but it's throwing this error!
> > ```
> >  python shodomain.py <MY-API-KEY> site.com
> > Traceback (most recent call last):
> >   File "shodomain.py", line 30, in <module>
> >     for item in data["data"]:
> > KeyError: 'data'
> > ```
> 
> How you solve this ?

not solved yet, not using this script anymore!
